using System;using System.Collections;using System.Text;using System.Globalization;
// Small strict JSON reader for Unity 5's bundled Mono; no external runtime dependency.
internal sealed class Json {
 string s;int p;Json(string text){s=text;}
 internal static object Read(string text){var j=new Json(text);object v=j.Value();j.Space();if(j.p!=text.Length)throw new FormatException("Trailing JSON");return v;}
 void Space(){while(p<s.Length&&(s[p]==' '||s[p]=='\t'||s[p]=='\r'||s[p]=='\n'))p++;}
 char Take(){if(p>=s.Length)throw new FormatException("Incomplete JSON");return s[p++];}
 void Need(char c){Space();if(Take()!=c)throw new FormatException("JSON delimiter");}
 object Value(){Space();if(p>=s.Length)throw new FormatException();char c=s[p];if(c=='"')return String();if(c=='{'){p++;var d=new Hashtable();Space();if(p<s.Length&&s[p]=='}'){p++;return d;}while(true){Space();string k=String();Need(':');if(d.ContainsKey(k))throw new FormatException("Duplicate JSON key");d.Add(k,Value());Space();c=Take();if(c=='}')return d;if(c!=',')throw new FormatException();}}if(c=='['){p++;var a=new ArrayList();Space();if(p<s.Length&&s[p]==']'){p++;return a;}while(true){a.Add(Value());Space();c=Take();if(c==']')return a;if(c!=',')throw new FormatException();}}foreach(string t in new[]{"true","false","null"})if(s.Substring(p).StartsWith(t,StringComparison.Ordinal)){p+=t.Length;return t=="null"?null:(object)(t=="true");}int start=p;if(c=='-')p++;int digits=p;while(p<s.Length&&(s[p]>='0'&&s[p]<='9'))p++;if(digits==p||(p-digits>1&&s[digits]=='0'))throw new FormatException();int number;if(!Int32.TryParse(s.Substring(start,p-start),NumberStyles.Integer,CultureInfo.InvariantCulture,out number))throw new FormatException("JSON integer range");return number;}
 string String(){if(Take()!='"')throw new FormatException();var b=new StringBuilder();while(true){char c=Take();if(c=='"')return b.ToString();if(c<' ')throw new FormatException();if(c!='\\'){b.Append(c);continue;}c=Take();switch(c){case '"':case '\\':case '/':b.Append(c);break;case 'b':b.Append('\b');break;case 'f':b.Append('\f');break;case 'n':b.Append('\n');break;case 'r':b.Append('\r');break;case 't':b.Append('\t');break;case 'u':if(p+4>s.Length)throw new FormatException();for(int i=0;i<4;i++){char h=s[p+i];if(!(h>='0'&&h<='9'||h>='a'&&h<='f'||h>='A'&&h<='F'))throw new FormatException("JSON Unicode escape");}b.Append((char)Int32.Parse(s.Substring(p,4),NumberStyles.HexNumber));p+=4;break;default:throw new FormatException();}}}
}
