using System;using System.IO;using System.Linq;using System.Collections.Generic;using Mono.Cecil;using Mono.Cecil.Cil;
class PatchRuntime {
 static IEnumerable<TypeDefinition> All(TypeDefinition t){yield return t;foreach(var n in t.NestedTypes)foreach(var v in All(n))yield return v;}
 static void Need(bool b,string s){if(!b)throw new Exception(s);}
 static void Main(string[] a){
 var resolver=new DefaultAssemblyResolver();resolver.AddSearchDirectory(a[4]);resolver.AddSearchDirectory(Path.GetDirectoryName(a[1]));var asm=AssemblyDefinition.ReadAssembly(a[0],new ReaderParameters{AssemblyResolver=resolver});var helper=AssemblyDefinition.ReadAssembly(a[1]);var runtime=helper.MainModule.GetType("CW3Runtime");Func<string,MethodReference> api=n=>asm.MainModule.ImportReference(runtime.Methods.Single(m=>m.Name==n));var originals=asm.MainModule.Types.SelectMany(All).SelectMany(t=>t.Methods).Where(m=>m.HasBody).ToDictionary(m=>m,m=>m.Body.Instructions.ToArray());var records=new List<string>();var pristine=AssemblyDefinition.ReadAssembly(a[6]);var guiMethods=new HashSet<MethodDefinition>();var guiButtons=new HashSet<Instruction>();var boundSites=new HashSet<Instruction>();
 Action<MethodDefinition,Instruction,Instruction[],Instruction[],MethodReference> edit=(m,i,before,after,replace)=>{int ix=Array.IndexOf(originals[m],i);Need(ix>=0,"Original site required");var il=m.Body.GetILProcessor();foreach(var x in before)il.InsertBefore(i,x);Instruction at=i;foreach(var x in after){il.InsertAfter(at,x);at=x;}if(replace!=null){i.OpCode=OpCodes.Call;i.Operand=replace;}records.Add(m.MetadataToken.ToInt32()+"\t"+ix+"\t"+before.Length+"\t"+after.Length+"\t"+(replace==null?"keep":"replace"));};
 Func<string,string,MethodDefinition> method=(t,n)=>asm.MainModule.Types.SelectMany(All).Single(x=>x.FullName==t).Methods.Single(m=>m.Name==n);
 foreach(var line in File.ReadAllLines(a[2])){var c=line.Split('\t');var origin=(MethodDefinition)(c[4]=="v9"?pristine:asm).MainModule.LookupToken(Int32.Parse(c[0]));var m=originals.Keys.Single(x=>x.FullName==origin.FullName);Need(Int32.Parse(c[1])<originals[m].Length,"Site beyond method "+m.FullName+" token "+c[0]+" #"+c[1]+" length "+originals[m].Length);var i=originals[m][Int32.Parse(c[1])];string source=System.Text.Encoding.UTF8.GetString(Convert.FromBase64String(c[3]));Need(boundSites.Add(i),"Duplicate physical display site "+c[2]);Need(i.OpCode==OpCodes.Ldstr&&(string)i.Operand==source,"Guarded ldstr "+c[2]);if(c.Length>5&&c[5]=="event")NativeEventCaptionAudit.Require(origin,origin.Body.Instructions[Int32.Parse(c[1])]);if(c.Length>5&&(c[5]=="gui"||c[5]=="label")){var consumer=GuiCaptionAudit.Consumer(m,i);if(c[5]=="gui"){guiMethods.Add(m);var call=(MethodReference)consumer.Operand;if(call.DeclaringType.FullName=="UnityEngine.GUILayout"&&call.Name=="Button")guiButtons.Add(consumer);}}var il=m.Body.GetILProcessor();edit(m,i,new Instruction[0],new[]{il.Create(OpCodes.Ldstr,source),il.Create(OpCodes.Call,api("Text"))},null);i.Operand=c[2];}
 var nativeEvents=originals.Keys.Single(m=>m.FullName=="System.Void GameEventManager::ShowEvent(GameEventManager/GAME_EVENT,System.String,UnityEngine.Vector2)");var eventInstructions=originals[nativeEvents];for(int n=0;n<eventInstructions.Length-1;n++){var i=eventInstructions[n];var next=eventInstructions[n+1];if(i.OpCode==OpCodes.Ldstr&&(next.OpCode==OpCodes.Stloc_3||next.OpCode==OpCodes.Stloc_S&&((VariableDefinition)next.Operand).Index==4))Need(boundSites.Contains(i),"Unbound native event caption: "+i.Operand);}
 foreach(string type in new[]{"SplashManager","MainMenu","GameSpace","MessageDialogManager","PreludeManager","EpilogueManager"}){var m=method(type,"Awake");var il=m.Body.GetILProcessor();edit(m,originals[m][0],new[]{il.Create(OpCodes.Call,api("Boot"))},new Instruction[0],null);}
 var process=method("UILabel","ProcessText");edit(process,originals[process][0],new[]{process.Body.GetILProcessor().Create(OpCodes.Ldarg_0),process.Body.GetILProcessor().Create(OpCodes.Call,api("PrepareLabel"))},new Instruction[0],null);var reads=originals[process].Where(i=>i.OpCode==OpCodes.Ldfld&&((FieldReference)i.Operand).Name=="mText").ToArray();Need(reads.Length==9,"UILabel reads");foreach(var i in reads.Skip(6)){var il=process.Body.GetILProcessor();edit(process,i,new Instruction[0],new[]{il.Create(OpCodes.Ldarg_0),il.Create(OpCodes.Call,api("ForLabel"))},null);}
 // Keep the original return instruction as the branch/leave target; append the hook after a nop.
 Action<MethodDefinition,Instruction,Instruction[],string> exit=(m,ret,args,name)=>{var il=m.Body.GetILProcessor();ret.OpCode=OpCodes.Nop;ret.Operand=null;edit(m,ret,new Instruction[0],args.Concat(new[]{il.Create(OpCodes.Call,api(name)),il.Create(OpCodes.Ret)}).ToArray(),null);records[records.Count-1]=records[records.Count-1].Replace("\tkeep","\treturn");};
 Action<MethodDefinition,string,bool> atReturn=(m,name,arg)=>{foreach(var ret in originals[m].Where(i=>i.OpCode==OpCodes.Ret)){var il=m.Body.GetILProcessor();exit(m,ret,arg?new[]{il.Create(OpCodes.Ldarg_0)}:new Instruction[0],name);}};
 var read=method("MessageDialogManager","ReadXML");foreach(var ret in originals[read].Where(i=>i.OpCode==OpCodes.Ret)){var il=read.Body.GetILProcessor();exit(read,ret,new[]{il.Create(OpCodes.Ldarg_0),il.Create(OpCodes.Ldarg_1)},"BindMessages");}
 var clear=method("MessageDialogManager","ClearMessages");var cl=clear.Body.GetILProcessor();edit(clear,originals[clear][0],new[]{cl.Create(OpCodes.Ldarg_0),cl.Create(OpCodes.Call,api("ClearMessages"))},new Instruction[0],null);
 foreach(var add in originals.Keys.Where(m=>m.DeclaringType.FullName=="MessageDialogManager"&&m.Name=="AddMessage"))atReturn(add,"MessageAdded",true);
 var remove=method("MessageDialogManager","RemoveMessage");foreach(var ret in originals[remove].Where(i=>i.OpCode==OpCodes.Ret)){var il=remove.Body.GetILProcessor();exit(remove,ret,new[]{il.Create(OpCodes.Ldarg_0),il.Create(OpCodes.Ldarg_1)},"MessageRemoved");}
 var system=method("SaveGameManager","LoadSystemInternal");var sysil=system.Body.GetILProcessor();var xmlLoads=originals[system].Where(i=>i.Operand is MethodReference&&((MethodReference)i.Operand).FullName=="System.Void System.Xml.XmlDocument::Load(System.IO.Stream)").ToArray();Need(xmlLoads.Length==1,"System XML load");var bytes=originals[system].Single(i=>i.Operand is MethodReference&&((MethodReference)i.Operand).FullName=="System.Byte[] UnityEngine.TextAsset::get_bytes()");Need(system.Body.Variables[0].VariableType.FullName=="UnityEngine.TextAsset"&&system.Body.Variables[3].VariableType.FullName=="System.Xml.XmlDocument","System source locals");edit(system,xmlLoads[0],new Instruction[0],new[]{sysil.Create(OpCodes.Ldloc_3),sysil.Create(OpCodes.Ldarg_0),sysil.Create(OpCodes.Ldloc_0),sysil.Create(OpCodes.Callvirt,(MethodReference)bytes.Operand),sysil.Create(OpCodes.Call,api("RegisterSystemDocument"))},null);
 var gameLoad=method("GameSpace","LoadMission");var gl=gameLoad.Body.GetILProcessor();var resourceBytes=originals[gameLoad].Where(i=>i.Operand is MethodReference&&((MethodReference)i.Operand).FullName=="System.Byte[] UnityEngine.TextAsset::get_bytes()").ToArray();Need(resourceBytes.Length==1&&gameLoad.Body.Variables[2].VariableType.FullName=="System.String","Mission resource key");edit(gameLoad,resourceBytes[0],new Instruction[0],new[]{gl.Create(OpCodes.Ldloc_2),gl.Create(OpCodes.Call,api("CaptureMissionResource"))},null);MissionScopePatch.Wrap(gameLoad,api("BeginMissionLoad"),api("EndMissionLoad"));records.Add(gameLoad.MetadataToken.ToInt32()+"\t-1\t0\t0\tmission_scope");
 var load=originals.Keys.Single(m=>m.DeclaringType.FullName=="SaveGameManager"&&m.Name=="LoadMission"&&m.Parameters[0].ParameterType.FullName=="System.Byte[]");var li=load.Body.GetILProcessor();var parsed=originals[load].Where(i=>i.Operand is MethodReference&&((MethodReference)i.Operand).FullName=="System.Void System.Xml.XmlDocument::Load(System.IO.Stream)").ToArray();Need(parsed.Length==1&&load.Body.Variables[1].VariableType.FullName=="System.Xml.XmlDocument","Mission XML load");edit(load,parsed[0],new Instruction[0],new[]{li.Create(OpCodes.Ldloc_1),li.Create(OpCodes.Call,api("RegisterMissionDocument"))},null);
 var keyNotice=method("ShieldKeyManager","ArrivedInOrbit");var keyNames=originals[keyNotice].Where(i=>i.OpCode==OpCodes.Ldfld&&((FieldReference)i.Operand).FullName=="System.String ShieldKeyManager::shieldKeyName").ToArray();Need(keyNames.Length==1,"Shield key display-name read");edit(keyNotice,keyNames[0],new Instruction[0],new[]{keyNotice.Body.GetILProcessor().Create(OpCodes.Ldarg_0),keyNotice.Body.GetILProcessor().Create(OpCodes.Call,api("ForName"))},null);
 var current=method("MessageDialogManager","set_currentMessage");var messages=originals[current].Where(i=>i.OpCode==OpCodes.Ldfld&&((FieldReference)i.Operand).Name=="message").ToArray();Need(messages.Length==2,"Message display reads");var cil=current.Body.GetILProcessor();edit(current,messages[1],new Instruction[0],new[]{cil.Create(OpCodes.Ldloc_0),cil.Create(OpCodes.Call,api("ForMessage"))},null);
 var commands=method("CrplCore","ProcessCommands");var writes=originals[commands].Where(i=>i.OpCode==OpCodes.Stfld&&((FieldReference)i.Operand).FullName=="System.String GameSpace::message").ToArray();Need(writes.Length==2,"CRPL message writes");foreach(var i in writes){var il=commands.Body.GetILProcessor();edit(commands,i,new[]{il.Create(OpCodes.Ldarg_0),il.Create(OpCodes.Call,api("CaptureCrpl"))},new Instruction[0],null);}
 var conversation=originals[commands].Where(i=>i.Operand is MethodReference&&((MethodReference)i.Operand).FullName=="System.Void CRPLTowerManager::AddMessageDialogMessage(System.Int32,System.String)").ToArray();Need(conversation.Length==1,"Native script conversation append");
 Need(commands.Body.Variables[10].VariableType.FullName=="System.Int32"&&commands.Body.Variables[25].VariableType.FullName=="System.String","Native conversation arguments");
 edit(commands,conversation[0],new Instruction[0],new[]{commands.Body.GetILProcessor().Create(OpCodes.Ldloc,commands.Body.Variables[10]),commands.Body.GetILProcessor().Create(OpCodes.Ldloc,commands.Body.Variables[25]),commands.Body.GetILProcessor().Create(OpCodes.Ldarg_0),commands.Body.GetILProcessor().Create(OpCodes.Call,api("BindScriptConversation"))},null);
 foreach(var ongui in guiMethods.Where(m=>m.DeclaringType.FullName!="GameSpace"||m.Name!="OnGUI")){var il=ongui.Body.GetILProcessor();edit(ongui,originals[ongui][0],new[]{il.Create(OpCodes.Call,api("GuiFont"))},new Instruction[0],null);}
 foreach(var m in guiMethods)foreach(var i in originals[m]){if(!guiButtons.Contains(i))continue;var mr=i.Operand as MethodReference;if(mr==null||mr.DeclaringType.FullName!="UnityEngine.GUILayout"||mr.Name!="Button"||mr.Parameters[0].ParameterType.FullName!="System.String")continue;
  if(mr.Parameters.Count==2&&mr.Parameters[1].ParameterType.FullName=="UnityEngine.GUILayoutOption[]")edit(m,i,new Instruction[0],new Instruction[0],api("LayoutButton"));
  else if(mr.Parameters.Count==3&&mr.Parameters[1].ParameterType.FullName=="UnityEngine.GUIStyle"&&mr.Parameters[2].ParameterType.FullName=="UnityEngine.GUILayoutOption[]")edit(m,i,new Instruction[0],new Instruction[0],api("LayoutStyledButton"));
 }
 var gui=method("GameSpace","OnGUI");var gr=originals[gui].Where(i=>i.OpCode==OpCodes.Ldfld&&((FieldReference)i.Operand).Name=="message").ToArray();Need(gr.Length==4,"GUI message reads");foreach(var i in gr.Skip(2))edit(gui,i,new Instruction[0],new[]{gui.Body.GetILProcessor().Create(OpCodes.Call,api("ForGuiMessage"))},null);edit(gui,originals[gui][0],new[]{gui.Body.GetILProcessor().Create(OpCodes.Call,api("GuiFont"))},new Instruction[0],null);
 int getters=0,setters=0;foreach(var pair in originals)foreach(var i in pair.Value){var mr=i.Operand as MethodReference;if(mr==null||mr.DeclaringType.FullName!="UnityEngine.TextMesh")continue;var m=pair.Key;var il=m.Body.GetILProcessor();if(mr.Name=="get_text"){edit(m,i,new Instruction[0],new Instruction[0],api("OriginalMesh"));getters++;}else if(mr.Name=="set_text"){if(m.Name=="set_planetName"||m.Name=="set_starName")edit(m,i,new[]{il.Create(OpCodes.Ldarg_0)},new Instruction[0],api("SetNamedMesh"));else edit(m,i,new Instruction[0],new Instruction[0],api("SetMesh"));setters++;}}
 MainMenuClickPatch.Apply(asm.MainModule);records.Add(method("MainMenu","OnMyMouseDown").MetadataToken.ToInt32()+"\t-1\t0\t0\tmain_menu_click");
 foreach(var m in originals.Keys)foreach(var i in m.Body.Instructions){if(i.OpCode==OpCodes.Br_S)i.OpCode=OpCodes.Br;else if(i.OpCode==OpCodes.Brfalse_S)i.OpCode=OpCodes.Brfalse;else if(i.OpCode==OpCodes.Brtrue_S)i.OpCode=OpCodes.Brtrue;else if(i.OpCode==OpCodes.Beq_S)i.OpCode=OpCodes.Beq;else if(i.OpCode==OpCodes.Bne_Un_S)i.OpCode=OpCodes.Bne_Un;else if(i.OpCode==OpCodes.Leave_S)i.OpCode=OpCodes.Leave;}
 asm.Write(a[3]);File.WriteAllLines(a[5],records);Console.WriteLine("Bound "+File.ReadAllLines(a[2]).Length+" ldstr sites, three UILabel reads, XML/CRPL display boundaries, "+getters+" raw TextMesh getters and "+setters+" display setters. Original models/scripts unchanged.");
 }
}
