using System;using Mono.Cecil;using Mono.Cecil.Cil;
class GuiCaptionContracts {
 static void Need(bool value,string reason){if(!value)throw new Exception(reason);}
 static void Main(){var a=AssemblyDefinition.CreateAssembly(new AssemblyNameDefinition("Fixture",new Version(1,0)),"Fixture",ModuleKind.Dll);var module=a.MainModule;
  var gui=new TypeReference("UnityEngine","GUILayout",module,module.TypeSystem.CoreLibrary);var label=new MethodReference("Label",module.TypeSystem.Void,gui);label.Parameters.Add(new ParameterDefinition(module.TypeSystem.String));
  var type=new TypeDefinition("","Fixture",TypeAttributes.Public,module.TypeSystem.Object);module.Types.Add(type);
  Func<MethodDefinition> method=()=>{var m=new MethodDefinition("Display",MethodAttributes.Static|MethodAttributes.Public,module.TypeSystem.Void);type.Methods.Add(m);return m;};
  var direct=method();var il=direct.Body.GetILProcessor();var text=il.Create(OpCodes.Ldstr,"Unit");il.Append(text);il.Append(il.Create(OpCodes.Call,label));il.Append(il.Create(OpCodes.Ret));Need(GuiCaptionAudit.Require(direct,text)==label.FullName,"Unit caption succeeds without changing internal unit key");
  var stored=method();stored.Body.Variables.Add(new VariableDefinition(module.TypeSystem.String));il=stored.Body.GetILProcessor();text=il.Create(OpCodes.Ldstr,"Started");var read=il.Create(OpCodes.Ldloc_0);il.Append(text);il.Append(il.Create(OpCodes.Stloc_0));il.Append(il.Create(OpCodes.Br,read));il.Append(read);il.Append(il.Create(OpCodes.Call,label));il.Append(il.Create(OpCodes.Ret));Need(GuiCaptionAudit.Require(stored,text)==label.FullName,"Single display local and join succeed");
  var field=new FieldDefinition("model",FieldAttributes.Public|FieldAttributes.Static,module.TypeSystem.String);type.Fields.Add(field);var unsafeMethod=method();il=unsafeMethod.Body.GetILProcessor();text=il.Create(OpCodes.Ldstr,"Unit");il.Append(text);il.Append(il.Create(OpCodes.Dup));il.Append(il.Create(OpCodes.Stsfld,field));il.Append(il.Create(OpCodes.Call,label));il.Append(il.Create(OpCodes.Ret));bool rejected=false;try{GuiCaptionAudit.Require(unsafeMethod,text);}catch(Exception){rejected=true;}Need(rejected,"Model mutation rejected even with later GUI call");
  var escaped=method();il=escaped.Body.GetILProcessor();text=il.Create(OpCodes.Ldstr,"Unit");il.Append(text);il.Append(il.Create(OpCodes.Dup));il.Append(il.Create(OpCodes.Call,label));il.Append(il.Create(OpCodes.Stsfld,field));il.Append(il.Create(OpCodes.Ret));rejected=false;try{GuiCaptionAudit.Require(escaped,text);}catch(Exception){rejected=true;}Need(rejected,"A copy used after the GUI call cannot change the model");
  var style=new MethodReference("GetStyle",module.TypeSystem.Object,new TypeReference("UnityEngine","GUISkin",module,module.TypeSystem.CoreLibrary));style.Parameters.Add(new ParameterDefinition(module.TypeSystem.String));var styleMethod=method();il=styleMethod.Body.GetILProcessor();text=il.Create(OpCodes.Ldstr,"Button");il.Append(text);il.Append(il.Create(OpCodes.Call,style));il.Append(il.Create(OpCodes.Pop));il.Append(il.Create(OpCodes.Ret));rejected=false;try{GuiCaptionAudit.Require(styleMethod,text);}catch(Exception){rejected=true;}Need(rejected,"Style identifiers rejected");
  var format=new MethodReference("Format",module.TypeSystem.String,module.TypeSystem.String);format.Parameters.Add(new ParameterDefinition(module.TypeSystem.String));format.Parameters.Add(new ParameterDefinition(module.TypeSystem.Object));
  var formatted=method();il=formatted.Body.GetILProcessor();text=il.Create(OpCodes.Ldstr,"Price: {0}");il.Append(text);il.Append(il.Create(OpCodes.Ldnull));il.Append(il.Create(OpCodes.Call,format));il.Append(il.Create(OpCodes.Call,label));il.Append(il.Create(OpCodes.Ret));Need(GuiCaptionAudit.Require(formatted,text)==label.FullName,"Formatted numeric caption reaches display only");
  var formatModel=method();il=formatModel.Body.GetILProcessor();text=il.Create(OpCodes.Ldstr,"Unit {0}");il.Append(text);il.Append(il.Create(OpCodes.Ldnull));il.Append(il.Create(OpCodes.Call,format));il.Append(il.Create(OpCodes.Stsfld,field));il.Append(il.Create(OpCodes.Ret));rejected=false;try{GuiCaptionAudit.Require(formatModel,text);}catch(Exception){rejected=true;}Need(rejected,"Formatted model strings remain rejected");
  Console.WriteLine("PASS GUI captions and isolated local; model writes and style identifiers rejected.");
 }
}
