using System;using System.IO;using System.Text;using System.Reflection;using System.Collections;using System.Collections.Generic;using System.Security.Cryptography;using UnityEngine;
public class CW3Debug : MonoBehaviour {
 [System.Runtime.InteropServices.DllImport("gdi32.dll", CharSet=System.Runtime.InteropServices.CharSet.Unicode)] static extern int AddFontResourceEx(string path,uint flags,System.IntPtr reserved);
 static CW3Debug instance;static BindingFlags flags=BindingFlags.Instance|BindingFlags.Static|BindingFlags.Public|BindingFlags.NonPublic;float next;string root;string lastUiClick="null";
 static object F(object o,string n){if(o==null)return null;for(Type t=o.GetType();t!=null;t=t.BaseType){var f=t.GetField(n,flags|BindingFlags.DeclaredOnly);if(f!=null)return f.GetValue(o);}return null;}
 static object P(object o,string n){if(o==null)return null;var p=o.GetType().GetProperty(n,flags);return p==null?null:p.GetValue(o,null);}
 static object Call(object o,string n,params object[] args){foreach(var m in o.GetType().GetMethods(flags))if(m.Name==n&&m.GetParameters().Length==args.Length)return m.Invoke(o,args);throw new Exception("Missing audited method "+n);}
 static Component Find(string type){foreach(Component c in UnityEngine.Object.FindObjectsOfType(typeof(Component)))if(c!=null&&c.GetType().Name==type)return c;throw new Exception("Scene does not contain "+type);}
 static Component Dialog(){Component sys=Find("SystemManager");var asm=sys.GetType().Assembly;var obj=(GameObject)asm.GetType("UberFind").GetMethod("Find",flags,null,new Type[]{typeof(string),typeof(string)},null).Invoke(null,new object[]{"UI Root (2D)","MessageDialog"});return obj.GetComponent(asm.GetType("MessageDialogManager"));}
 static string Q(object s){return "\""+(s==null?"":s.ToString()).Replace("\\","\\\\").Replace("\"","\\\"").Replace("\r","\\r").Replace("\n","\\n").Replace("\t","\\t")+"\"";}
 static string PathOf(Transform t){string s=t.name;while(t.parent!=null){t=t.parent;s=t.name+"/"+s;}return s;}
 static string Hash(string p){using(var f=File.OpenRead(p))using(var h=SHA256.Create())return BitConverter.ToString(h.ComputeHash(f)).Replace("-","").ToLowerInvariant();}
 public static void Boot(){try{if(instance!=null)return;string dir=Path.Combine(Application.dataPath,"cw3-debug");string enable=Path.Combine(dir,"enabled.txt");if(!File.Exists(enable))return;string expected=File.ReadAllText(enable).Trim();string actual=Hash(Path.Combine(Application.dataPath,"Managed/Assembly-CSharp.dll"));if(expected.Length!=64||expected!=actual)return;var go=new GameObject("CW3Debug (explicitly enabled)");DontDestroyOnLoad(go);instance=go.AddComponent<CW3Debug>();instance.root=dir;File.WriteAllText(Path.Combine(dir,"ready.json"),"{\"enabled\":true,\"assembly_sha256\":"+Q(actual)+"}");}catch(Exception e){Debug.Log("[CW3Debug] boot failed: "+e.GetType().Name);}}
 void Update(){if(Application.loadedLevelName=="MainMenu"&&Input.GetMouseButtonDown(0))try{lastUiClick=UiProbe();}catch(Exception e){lastUiClick="{\"error\":"+Q(e.Message)+"}";}if(Time.realtimeSinceStartup<next)return;next=Time.realtimeSinceStartup+0.25f;if(!File.Exists(Path.Combine(root,"enabled.txt"))){Destroy(gameObject);instance=null;return;}string p=Path.Combine(root,"request.txt");if(!File.Exists(p))return;string request=File.ReadAllText(p);File.Delete(p);string[] v=request.Trim().Split('\t');string id=v.Length>0?v[0]:"invalid";try{if(v.Length<2||v.Length>3||id.Length>64)throw new Exception("Invalid request");foreach(char c in id)if(!Char.IsLetterOrDigit(c)&&c!='-'&&c!='_')throw new Exception("Invalid id");string result=Execute(v[1],v.Length==3?v[2]:"");File.WriteAllText(Path.Combine(root,"response.json"),"{\"id\":"+Q(id)+",\"command\":"+Q(v[1])+",\"ok\":true,\"result\":"+result+"}");}catch(Exception e){File.WriteAllText(Path.Combine(root,"response.json"),"{\"id\":"+Q(id)+",\"ok\":false,\"error\":"+Q(e.InnerException==null?e.Message:e.InnerException.Message)+"}");}}
 string Execute(string command,string arg){
  if(command=="font_probe"&&arg==""){
   string file=Path.Combine(Application.dataPath,"../CW3Localization/font.ttf");int registered=AddFontResourceEx(file,16,IntPtr.Zero);Type runtime=Type.GetType("CW3Runtime, CW3Runtime",false);var font=runtime==null?Font.CreateDynamicFontFromOSFont("CW3 Sans SC External",20):(Font)runtime.GetField("external",flags).GetValue(null);font.RequestCharactersInTexture("字体外置验证龘㐀",20,FontStyle.Normal);CharacterInfo ci;bool glyph=font.GetCharacterInfo('龘',out ci,20,FontStyle.Normal);return "{\"registered\":"+registered+",\"font\":"+Q(font.name)+",\"has_character\":"+(font.HasCharacter('龘')?"true":"false")+",\"glyph\":"+(glyph?"true":"false")+",\"advance\":"+ci.advance+"}";
  }
  if(command=="runtime_probe"&&arg==""){Type rt=Type.GetType("CW3Runtime, CW3Runtime",true);var report=(IDictionary)rt.GetMethod("RuntimeReport").Invoke(null,null);var font=(Font)report["font"];return "{\"bound_xml\":"+report["bound_xml"]+",\"crpl_id\":"+Q(report["crpl_id"])+",\"targets\":"+report["targets"]+",\"translations\":"+report["translations"]+",\"font\":"+Q(font)+",\"unknown_fallback\":"+Q(rt.GetMethod("Text").Invoke(null,new object[]{"unknown.id","RAW"}))+",\"source_fallback\":"+Q(rt.GetMethod("Text").Invoke(null,new object[]{"text.63b374e8d84d967e","UNREVIEWED"}))+",\"glyph\":"+(font!=null&&font.HasCharacter('龘')?"true":"false")+"}";}
  if(command=="discovery_probe"&&arg=="")return (string)Type.GetType("CW3Runtime, CW3Runtime",true).GetMethod("DiscoveryStatus").Invoke(null,null);
  if(command=="snapshot"&&arg=="")return Snapshot();
  if(command=="ui_probe"&&arg=="")return "{\"current\":"+UiProbe()+",\"last_main_menu_click\":"+lastUiClick+"}";
  if(command=="menu_open"||command=="menu_close"){if(arg!="")throw new Exception("No argument allowed");Component game=Find("GameSpace");Call(game,"set_paused",command=="menu_open");Call(game,"ShowMenu",command=="menu_open");return "{\"invoked\":\"GameSpace.ShowMenu\"}";}
  if(command=="prelude_replay"&&arg==""){Find("SystemManager");if(Application.loadedLevelName!="Gal")throw new Exception("Gal only");bool available=false;foreach(Component c in Resources.FindObjectsOfTypeAll(typeof(Component)))if(c!=null&&c.name=="ReplayPreludeButton"&&c.gameObject.activeInHierarchy&&c.GetComponent<Collider>()!=null&&c.GetComponent<Collider>().enabled)available=true;if(!available)throw new Exception("Normal replay prelude button unavailable");Application.LoadLevel("Prelude");return "{\"invoked\":\"GalGUIHandlers replay Prelude branch\"}";}
  if(command=="prelude_return"&&(arg=="awaken"||arg=="skip")){if(Application.loadedLevelName!="Prelude")throw new Exception("Prelude only");string name=arg=="awaken"?"AwakenButton":"SkipButton";bool available=false;foreach(Component c in Resources.FindObjectsOfTypeAll(typeof(Component)))if(c!=null&&c.name==name&&c.gameObject.activeInHierarchy&&c.GetComponent<Collider>()!=null&&c.GetComponent<Collider>().enabled)available=true;if(!available)throw new Exception("Normal prelude return button unavailable");Application.LoadLevel("Gal");return "{\"invoked\":\"PreludeGUIHandlers normal return branch\"}";}
  if(command=="archive_next"&&arg==""){Component dialog=Dialog();if(!dialog.gameObject.activeInHierarchy)throw new Exception("Open archive first");int current=(int)P(dialog,"currentMessage");var rows=(IList)F(dialog,"messages");if(current+1>=rows.Count)throw new Exception("Last message reached");Call(dialog,"set_currentMessage",current+1);return MessageRows(dialog);}
  if(command=="archive_close"&&arg==""){Component dialog=Dialog();if(!dialog.gameObject.activeInHierarchy)throw new Exception("Open archive first");Call(dialog,"Hide");return "{\"invoked\":\"MessageDialogManager.Hide\"}";}
  if(command=="archive_open"&&arg==""){if(Application.loadedLevelName!="Gal")throw new Exception("Gal only");Find("SystemManager");bool available=false;foreach(Component c in Resources.FindObjectsOfTypeAll(typeof(Component)))if(c!=null&&c.name=="ArchivedTransmissions"&&c.gameObject.activeInHierarchy&&c.GetComponent<Collider>()!=null&&c.GetComponent<Collider>().enabled)available=true;if(!available)throw new Exception("Normal archive button unavailable");Component dialog=Dialog();var rows=(IList)F(dialog,"messages");if(rows==null||rows.Count==0)throw new Exception("No archived messages");Call(dialog,"Show");Call(dialog,"set_currentMessage",0);return MessageRows(dialog);}
  if(command=="message_probe"&&arg=="")return MessageRows(Dialog());
  if(command=="dialogue_replay"&&arg==""){Call(Find("SystemManager"),"HandleArchivedTransmissionsButton");return "{\"invoked\":\"SystemManager.HandleArchivedTransmissionsButton\"}";}
  if(command=="select_planet"){
   if(arg!="Tempus"&&arg!="Carcere")throw new Exception("Only audited first-system planet IDs allowed");Component sys=Find("SystemManager");object target=Call(sys,"GetGalObjectByGUID",arg);if(target==null||target.GetType().Name!="PlanetManager")throw new Exception("Planet absent");if((bool)P(target,"shielded"))throw new Exception("Planet locked: normal shield precondition retained");object ship=F(sys,"ship");Call(ship,"SetTarget",target,false);return "{\"invoked\":\"GalShipManager.SetTarget\",\"wait_for_arrival\":true}";
  }
  if(command=="planet_preview"&&arg=="Tempus"){Component sys=Find("SystemManager");object planet=P(sys,"currentGalObject");if(planet==null||P(planet,"GUID").ToString()!="Tempus"||(bool)P(planet,"shielded"))throw new Exception("Select unlocked Tempus first");Call(planet,"set_hovered",true);return "{\"invoked\":\"PlanetManager.set_hovered\"}";}
  if(command=="description"){
   Find("GameSpace");int index=arg=="Collector"?0:arg=="Relay"?1:arg=="Mortar"?9:-1;if(index<0)throw new Exception("Only audited description samples allowed");var asm=Find("GameSpace").GetType().Assembly;var type=asm.GetType("TechArtifactManager");var method=type.GetMethod("GetTechDescription",flags);Type parameter=method.GetParameters()[0].ParameterType;object key=parameter.IsEnum?Enum.ToObject(parameter,index):Convert.ChangeType(index,parameter);string description=(string)method.Invoke(null,new object[]{key});asm.GetType("InfoPanel").GetMethod("ShowInfoMessage",flags,null,new Type[]{typeof(string)},null).Invoke(null,new object[]{description});return "{\"invoked\":\"GetTechDescription + normal InfoPanel\",\"text\":"+Q(description)+"}";
  }
  if(((command=="load_auto"||command=="restart_mission")&&arg=="")||(command=="load_slot"&&arg=="0")){Component sys=Find("SystemManager");object planet=P(sys,"currentGalObject");if(planet==null||P(planet,"GUID").ToString()!="Tempus"||(bool)P(planet,"shielded"))throw new Exception("Select unlocked Tempus first");bool enabled=false;foreach(Component button in Resources.FindObjectsOfTypeAll(typeof(Component)))if(button!=null&&(command=="restart_mission"?button.GetType().Name=="UIButtonColor":button.GetType().Name=="UIButton")&&button.name==(command=="load_auto"?"LoadSlotAutoButton":command=="load_slot"?"LoadSlot0Button":"LoadHUDRestartButton")&&button.gameObject.activeInHierarchy&&button.GetComponent<Collider>()!=null&&button.GetComponent<Collider>().enabled)enabled=true;if(!enabled)throw new Exception("Normal load/restart button unavailable");Call(sys,"LaunchMission",command=="load_auto"?"auto":command=="load_slot"?"0":"");return "{\"invoked\":\"SystemManager.LaunchMission("+(command=="load_auto"?"auto":command=="load_slot"?"0":"new")+")\"}";}
  if(command=="start_mission"&&arg==""){Component sys=Find("SystemManager");object planet=P(sys,"currentGalObject");if(planet==null||planet.GetType().Name!="PlanetManager"||(bool)P(planet,"shielded"))throw new Exception("No unlocked planet selected");Call(sys,"StartMission");return "{\"invoked\":\"SystemManager.StartMission\"}";}
  throw new Exception("Command not allowed");
 }
 string UiProbe(){
  Type cameraType=null;foreach(var asm in AppDomain.CurrentDomain.GetAssemblies()){cameraType=asm.GetType("UICamera",false);if(cameraType!=null)break;}
  var hoverField=cameraType==null?null:cameraType.GetField("hoveredObject",flags);var hovered=hoverField==null?null:hoverField.GetValue(null) as GameObject;
  Type rt=Type.GetType("CW3Runtime, CW3Runtime",false);var guiField=rt==null?null:rt.GetField("guiExternal",flags);Font gui=guiField==null?null:guiField.GetValue(null) as Font;
  var s=new StringBuilder("{\"scene\":"+Q(Application.loadedLevelName)+",\"screen\":"+Q(Screen.width+"x"+Screen.height)+",\"mouse\":"+Q(Input.mousePosition)+",\"hovered\":"+Q(hovered==null?null:PathOf(hovered.transform))+",\"gui_font_size\":"+(gui==null?0:gui.fontSize)+",\"controls\":[");bool first=true;
  foreach(Component c in UnityEngine.Object.FindObjectsOfType(typeof(Component))){if(c==null)continue;string t=c.GetType().Name;if(t!="MainMenuSpriteManager"&&t!="TexturePickerManager"&&t!="ResizeMapManager")continue;if(!first)s.Append(',');first=false;Collider collider=c.GetComponent<Collider>();s.Append("{\"type\":"+Q(t)+",\"path\":"+Q(PathOf(c.transform))+",\"locked\":"+Q(P(c,"locked"))+",\"window_rect\":"+Q(F(c,"windowRect"))+",\"started\":"+Q(F(c,"started"))+",\"showing_gui\":"+Q(F(c,"showingGUI"))+",\"collider_enabled\":"+(collider!=null&&collider.enabled?"true":"false")+",\"collider_bounds\":"+Q(collider==null?null:(object)collider.bounds)+"}");}
  s.Append("],\"ray_hits\":[");Camera camera=Camera.main;if(camera!=null){RaycastHit[] hits=Physics.RaycastAll(camera.ScreenPointToRay(Input.mousePosition));for(int i=0;i<hits.Length&&i<12;i++){if(i>0)s.Append(',');Collider c=hits[i].collider;s.Append("{\"path\":"+Q(c==null?null:PathOf(c.transform))+",\"distance\":"+Q(hits[i].distance)+"}");}}
  return s.Append("]}").ToString();
 }
 string MessageRows(Component dialog){Type rt=Type.GetType("CW3Runtime, CW3Runtime",true);var rows=(IList)F(dialog,"messages");var method=rt.GetMethod("MessageReport");var s=new StringBuilder("{\"current\":"+Q(P(dialog,"currentMessage"))+",\"rows\":[");for(int i=0;i<rows.Count;i++){if(i>0)s.Append(',');var report=(IDictionary)method.Invoke(null,new object[]{F(rows[i],"message"),rows[i]});s.Append("{\"status\":"+Q(report["status"])+",\"index\":"+i+",\"source\":"+Q(report["source"])+",\"display\":"+Q(report["display"])+",\"id\":"+Q(report["id"])+",\"context\":"+Q(report["context"])+"}");}return s.Append("]}").ToString();}
 string Snapshot(){var s=new StringBuilder();s.Append("{\"scene\":"+Q(Application.loadedLevelName)+",\"time\":"+Q(Time.realtimeSinceStartup)+",\"components\":[");bool first=true;
  foreach(Component c in Resources.FindObjectsOfTypeAll(typeof(Component))){if(c==null)continue;string t=c.GetType().Name;if(t!="UILabel"&&t!="UISprite"&&t!="UIPanel"&&t!="UIDrawCall"&&t!="PlanetManager"&&t!="SystemManager"&&t!="GameSpace"&&t!="MessageDialogManager"&&t!="TextMesh"&&t!="StarManager")continue;if(c.gameObject.hideFlags!=HideFlags.None&&t!="UIDrawCall")continue;if(!first)s.Append(',');first=false;Material mat=P(c,"material") as Material;var ren=c.GetComponent<Renderer>();var font=F(c,"mFont");var fade=c.GetComponent("SetColor");var fadeMat=F(fade,"material") as Material;var runtime=Type.GetType("CW3Runtime, CW3Runtime",false);var mesh=c as TextMesh;var meshReport=runtime==null||mesh==null?null:(IDictionary)runtime.GetMethod("MeshReport").Invoke(null,new object[]{mesh});s.Append("{\"render_status\":"+Q(meshReport==null?null:meshReport["status"])+",\"material_owned\":"+(meshReport!=null&&(bool)meshReport["material_owned"]?"true":"false")+",\"fade_alpha\":"+Q(F(fade,"alpha"))+",\"fade_material\":"+Q(fadeMat==null?null:(object)fadeMat.GetInstanceID())+",\"renderer_material\":"+Q(ren==null||ren.sharedMaterial==null?null:(object)ren.sharedMaterial.GetInstanceID())+",\"renderer_color\":"+Q(ren==null||ren.sharedMaterial==null?null:(object)ren.sharedMaterial.color)+",\"mesh_font\":"+Q(P(c,"font"))+",\"type\":"+Q(t)+",\"path\":"+Q(PathOf(c.transform))+",\"active\":"+(c.gameObject.activeInHierarchy?"true":"false")+",\"position\":"+Q(c.transform.position)+",\"local_position\":"+Q(c.transform.localPosition)+",\"depth\":"+Q(P(c,"depth"))+",\"text\":"+Q(P(c,"text"))+",\"processed_text\":"+Q(P(c,"processedText"))+",\"panel\":"+Q(F(c,"mPanel"))+",\"material\":"+Q(mat)+",\"queue\":"+(mat==null?-1:mat.renderQueue)+",\"shader\":"+Q(mat==null?null:mat.shader)+",\"font\":"+Q(font)+",\"dynamic_font\":"+Q(P(font,"dynamicFont"))+",\"verts\":"+Q(F(F(F(c,"mGeom"),"verts"),"size"))+",\"guid\":"+Q(P(c,"GUID"))+",\"raw_message\":"+Q(F(c,"message"))+",\"shielded\":"+Q(P(c,"shielded"))+",\"current_planet\":"+Q(P(c,"currentGalObject"))+",\"renderer_shader\":"+Q(ren==null||ren.sharedMaterial==null?null:ren.sharedMaterial.shader)+",\"renderer_queue\":"+(ren==null||ren.sharedMaterial==null?-1:ren.sharedMaterial.renderQueue)+"}");}
  s.Append("]}");return s.ToString();
 }
}
