using System;using System.Linq;using Mono.Cecil;using Mono.Cecil.Cil;
class Patch {
 static void Main(string[] a){var resolver=new DefaultAssemblyResolver();resolver.AddSearchDirectory(a[2]);resolver.AddSearchDirectory(System.IO.Path.GetDirectoryName(a[1]));var asm=AssemblyDefinition.ReadAssembly(a[0],new ReaderParameters{AssemblyResolver=resolver});var helper=AssemblyDefinition.ReadAssembly(a[1]);var type=helper.MainModule.GetType("CW3Rendering");var ordered=asm.MainModule.ImportReference(type.Methods.Single(x=>x.Name=="Ordered"));var sync=asm.MainModule.ImportReference(type.Methods.Single(x=>x.Name=="SyncDrawCall"));
 foreach(string n in new[]{"UILabel","UISprite","UITexture"}){var m=asm.MainModule.GetType(n).Methods.Single(x=>x.Name=="get_material");var il=m.Body.GetILProcessor();int count=0;foreach(var i in m.Body.Instructions.Where(x=>x.OpCode==OpCodes.Ret).ToArray()){i.OpCode=OpCodes.Ldarg_0;i.Operand=null;var call=il.Create(OpCodes.Call,ordered);il.InsertAfter(i,call);il.InsertAfter(call,il.Create(OpCodes.Ret));count++;}Widen(m);Console.WriteLine(n+" material returns wrapped: "+count);}
 var render=asm.MainModule.GetType("UIDrawCall").Methods.Single(x=>x.Name=="OnWillRenderObject");var ril=render.Body.GetILProcessor();foreach(var i in render.Body.Instructions.Where(x=>x.OpCode==OpCodes.Ret).ToArray()){i.OpCode=OpCodes.Ldarg_0;i.Operand=null;var call=ril.Create(OpCodes.Call,sync);ril.InsertAfter(i,call);ril.InsertAfter(call,ril.Create(OpCodes.Ret));}Widen(render);
 // The shield-condition display dispatch must use immutable GUIDs, not localized names.
 var shield=asm.MainModule.GetType("SystemManager").Methods.Single(x=>x.Name=="ShowStorySystemMessageForPlanet");var guid=asm.MainModule.GetType("GalObjectManager").Methods.Single(x=>x.Name=="get_GUID");int changed=0;foreach(var i in shield.Body.Instructions){var mr=i.Operand as MethodReference;if(mr!=null&&mr.DeclaringType.Name=="PlanetManager"&&mr.Name=="get_planetName"){i.Operand=guid;changed++;}}if(changed!=12)throw new Exception("Unexpected shield dispatch count");Console.WriteLine("Shield explanation dispatches corrected to GUID: "+changed);asm.Write(a[3]);
 }
 static void Widen(MethodDefinition m){foreach(var i in m.Body.Instructions){if(i.OpCode==OpCodes.Br_S)i.OpCode=OpCodes.Br;else if(i.OpCode==OpCodes.Brfalse_S)i.OpCode=OpCodes.Brfalse;else if(i.OpCode==OpCodes.Brtrue_S)i.OpCode=OpCodes.Brtrue;else if(i.OpCode==OpCodes.Beq_S)i.OpCode=OpCodes.Beq;else if(i.OpCode==OpCodes.Bne_Un_S)i.OpCode=OpCodes.Bne_Un;else if(i.OpCode==OpCodes.Leave_S)i.OpCode=OpCodes.Leave;}}
}
